# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    avatar_directory: '%kernel.project_dir%/public/uploads/avatars'
    avatar_url: '/uploads/avatars'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    App\EventSubscriber\QuackSubscriber:
        # Injecter le service 'security.helper' comme dépendance de votre subscriber
        arguments:
            - '@security.helper'
        # Ajouter le tag 'doctrine.event_subscriber' pour lier votre subscriber à l'événement 'prePersist'
        tags:
            - { name: doctrine.event_subscriber }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
